language: cpp
sudo: true
dist: trusty
depth: 3

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55translations qt55tools
 - sudo apt-get install libsqlite3-dev libzip-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libuchardet-dev libgl1-mesa-dev
 - source /opt/qt55/bin/qt55-env.sh ; export QTHOME=/opt/qt55 
 - git clone https://github.com/datasift/libcld2; cd libcld2 && make && sudo make install
 
script:
 - qmake
 - make
